version: '2'

# docker volume create --name postgres-data -d local

services:
  postgres:
    restart: always
    container_name: postgres_db
    image: postgres:latest
    #tty: true
    ports:
      - "5432:5432"
    volumes:
       - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
      COMPOSE_CONVERT_WINDOWS_PATHS: "true"
      #PGDATA: /tmp

volumes:
  postgres-data:
      external: true